name: Checkout and deploy
on:
  push:
    branches: [main, github-actions]

jobs:
  checkout:
    name: 'Checkout'
    runs-on:
      labels: [self-hosted, sangsu]
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

  install_dependancy:
    name: 'Install dependancy'
    needs: [checkout]
    runs-on:
      labels: [self-hosted, sangsu]
    steps:
      - uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - run: npm cache verify
      - run: npm ci

  checkout_config:
    name: 'Checkout config'
    needs: [checkout]
    runs-on:
      labels: [self-hosted, sangsu]
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'main'
          repository: wnynya/api.wany.io-config
          token: ${{ secrets.CONFIG_TOKEN }}
          path: './config'
          clean: false

  deploy:
    name: 'Deploy'
    needs: [checkout, checkout_config, install_dependancy]
    runs-on:
      labels: [self-hosted, sangsu]
    steps:
      - run: chmod 777 ./start.sh
      - run: RUNNER_TRACKING_ID="" && ./start.sh
